"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class command(object):
    __slots__ = ["forward", "turn"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.forward = 0.0
        self.turn = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.forward, self.turn))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return command._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = command()
        self.forward, self.turn = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if command in parents: return 0
        tmphash = (0x58b14116f047b374) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if command._packed_fingerprint is None:
            command._packed_fingerprint = struct.pack(">Q", command._get_hash_recursive([]))
        return command._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

